### ISSUE TITLE
After updating some plugins seemed to go away and unable to reinstall

### ISSUE THREAD

**Issue by Jese44** [cp2004/Octoprint-Upgrade-To-Py3#17]
Upgrade itself went fine and it wasnt such a big deal to reinstall a few (~3-4) plugins, but this Octohue https://plugins.octoprint.org/plugins/octohue/ does not want to install.... oh well.. it says it installs it, but the plugin itself is missing from settings.

**Comment by Jese44** [comment]
Can't thell wether this bug is from this python upgrade or octohue itself, but this occured after upgrading to python. Someone else is having problem with installing octohue too... https://github.com/entrippy/OctoPrint-OctoHue/issues/39

**Comment by cp2004** [comment]
Not my problem, sorry 🙁 

Provide an `octoprint.log` to the plugin author, it likely tells you *exactly* why it has failed to load.
