### ISSUE TITLE
[Bug] Installation failes after fresh install

### ISSUE THREAD

**Issue by nicedevil007** [cp2004/Octoprint-Upgrade-To-Py3#25]
I installed octopi from scratch => nightly build from today (0.18, 2020-09-23).

I get this error:

![image](https://user-images.githubusercontent.com/17103076/94048026-2f32b300-fdd3-11ea-8454-06391b6731a3.png)

**Comment by jneilliii** [comment]
The nightly builds already come bundled with Python3, you don't need to upgrade.

**Comment by nicedevil007** [comment]
ahhaha... ok then it was just an old version of 0.18 that didn't come with python3 activated (my installation was a bit older since is reinstalled from scratch today)

ok thanks! problem solved, but now the bed level visualizer is lacking of support. but not a prob from you :D

**Comment by jneilliii** [comment]
There's a known issue on the Bed Leveler's plugin Repo, it's the same thing...you just need to run `sudo apt install libatlas-base-dev` on your pi and then the plugin will work fine.

**Comment by nicedevil007** [comment]
> There's a known issue on the Bed Leveler's plugin Repo, it's the same thing...you just need to run `sudo apt install libatlas-base-dev` on your pi and then the plugin will work fine.

<3
