### ISSUE TITLE
blocked because octopi version is too old

### ISSUE THREAD

**Issue by pjratl** [cp2004/Octoprint-Upgrade-To-Py3#28]
I have upgraded the system using the standard apt-get commands to latest version but your script is checking for a octopi version file I believe any way around this?

**Comment by cp2004** [comment]
If you think it will work, try using the command line flag `--custom` and it should get around that check. Be warned, potential system instability lies ahead.

**Comment by cp2004** [comment]
Also, standard `apt upgrade` is not sufficient.

**Comment by pjratl** [comment]
yeah just figured that out manually installing building python 3.8 now

**Comment by pjratl** [comment]
ok upgraded python to3.8
tried the --custom switch

got this
Detecting system info...
OctoPi version: 0.16.0
Your OctoPi install does not support upgrading OctoPrint to Python 3 - Please upgrade your install.
Details: https://github.com/cp2004/Octoprint-Upgrade-To-Py3#what-do-i-do-if-my-system-is-not-supported
Looks like your OS is not linux

**Comment by pjratl** [comment]
closing this issue just did a clean install and restore everything works fine
