### ISSUE TITLE
[Bug] Describe your bug

### ISSUE THREAD

**Issue by leoheck** [cp2004/Octoprint-Upgrade-To-Py3#30]
It is not a bug, it is a question.
If I don't use virtual env, which path should I add there? Nothing seems to work.

**Comment by cp2004** [comment]
Not supported by the script unfortunately. I recommend you backup your instance (using built in feature to OctoPrint), then install OctoPrint on your system Python 3, then restore. Although virtualenvs make it quite a lot easier to manage.

**Comment by leoheck** [comment]
Perfect, thank you for the instructions. 
What do you think about adding a note like this on README? It will help users like me.

**Comment by cp2004** [comment]
There is now a [Supported Platforms](https://github.com/cp2004/Octoprint-Upgrade-To-Py3#supported-platforms) section in the Readme, that should hopefully make this clear.
