### ISSUE TITLE
[Bug] Script Unable to parse Python version string.

### ISSUE THREAD

**Issue by Githubber616** [cp2004/Octoprint-Upgrade-To-Py3#38]
I post it here cause it said so:
```
Unable to parse Python version string. Please report to me the line below that has caused problems....
[]
Virtual environment is already Python 3, are you sure you need an upgrade?
Please try again
```

**Comment by cp2004** [comment]
Could you activate your OctoPrint virtual environment and run `python --version`? Thanks.

**Comment by cp2004** [comment]
Hey @Githubber616 did you have a chance to check the Python version?

**Comment by cp2004** [comment]
I'll have to take that as a no.... 🙁 

Feel free to request a reopen if you can provide the additional information requested.
