### ISSUE TITLE
upgrade requires python 3.6?

### ISSUE THREAD

**Issue by nickm324** [cp2004/Octoprint-Upgrade-To-Py3#48]
**Describe the bug**
When I attempt to run the commands to upgrade it says I need python 3.6 to upgrade to python 3.6

**Script output**
 python3 upgrade.py
This script requires running using Python 3.6+
Please run using 'python3 upgrade.py'
Please check the system requirements at https://github.com/cp2004/Octoprint-Upgrade-To-Py3#requirements

**Script version**
SCRIPT_VERSION = '2.2.0'

**OctoPrint Version**
OctoPrint 1.7.0

**Comment by cp2004** [comment]
The script requires Python 3.6 or newer installed to run. It then uses that Python install to upgrade your OctoPrint virtual environment to use Python 3. It's up to you to make sure Python 3.6 is available on your system.

Please see https://github.com/cp2004/Octoprint-Upgrade-To-Py3#requirements for the detailed requirements.
