### ISSUE TITLE
X server needed to run that script ?

### ISSUE THREAD

**Issue by mameniac** [cp2004/Octoprint-Upgrade-To-Py3#51]
**Describe the bug**
after dowenloading the script I made it executable using sudo chmod +x upgrade.py and I executed the script using sudo.
Right after that the script is telling me that its not able to open the X server

**Script output**
Please paste the ***complete*** output of the script in the box below:
```
sudo ./upgrade.py
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/360.
./upgrade.py: 19: ./upgrade.py: Syntax error: "(" unexpected (expecting "then")

```

**Script version**
SCRIPT_VERSION = '2.2.0'

**OctoPrint Version**
octoprint.version: 1.6.1

**Relevant plugins that may have caused errors**
If you're having trouble with a particular part, please include your installed plugins

**Additional information**
Screenshots, links to docs, etc.
![Screenshot_1](https://user-images.githubusercontent.com/28724947/137172913-b9377087-c77d-46a5-ab3f-52536adf7bd4.png)

**Comment by cp2004** [comment]
Try again, correctly follow the instructions about how to use this script, then return if you still can't do it, but only if you have followed the instructions.

https://github.com/cp2004/Octoprint-Upgrade-To-Py3#running-the-script
