### ISSUE TITLE
[Bug] UnicodeDecodeError running `sudo apt-get update`

### ISSUE THREAD

**Issue by TheRealOtto** [cp2004/Octoprint-Upgrade-To-Py3#52]
**Describe the bug**
Upgrade script exits with error (see below)

**Script output**
Please paste the ***complete*** output of the script in the box below:
pi@octopi:~ $ curl -L https://get.octoprint.org/py3/upgrade.py --output upgrade.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0   1495      0 --:--:-- --:--:-- --:--:--  1495
100 27452  100 27452    0     0  84728      0 --:--:-- --:--:-- --:--:-- 84728

pi@octopi:~ $ python3 upgrade.py
OctoPrint Upgrade to Py 3 (v2.2.1)

This script will move your existing OctoPrint configuration from Python 2 to Python 3
This script requires an internet connection and it will disrupt any ongoing print jobs.

It will install the latest version of OctoPrint and all plugins.
No configuration or other files will be overwritten

Press [enter] to continue or ctrl-c to quit

Checking system info...
Detected OctoPi version 0.17.0
Checking OctoPrint version...
OctoPrint version: 1.7.0
Reading installed plugins...

Plugins installed
- GPIO Control
If you think there is something missing from here, please check the list of plugins in OctoPrint
Press [enter] to continue or ctrl-c to quit

Updating package list...
Checking package list for python3-dev
Installing python3-dev...
Traceback (most recent call last):
  File "upgrade.py", line 679, in <module>
    run_apt_install("python3-dev", backup_location)
  File "upgrade.py", line 177, in run_apt_install
    output, poll = run_sys_command(["sudo", "apt-get", "install", package, "-y"], sudo=True)
  File "upgrade.py", line 118, in run_sys_command
    print(output_line, end="")
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffd' in position 14: ordinal not in range(256)
pi@octopi:~ $ Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='ISO-8859-1'>
BrokenPipeError: [Errno 32] Daten�bergabe unterbrochen (broken pipe)
E: Unterprozess /usr/bin/apt-listchanges --apt || test $? -lt 10 hat Fehlercode zur�ckgegeben (1)
E: Failure running script /usr/bin/apt-listchanges --apt || test $? -lt 10

**Script version**
You can find this printed in the first line of the script
v2.2.1

**OctoPrint Version**
OctoPrint 1.7.0

**Relevant plugins that may have caused errors**
If you're having trouble with a particular part, please include your installed plugins

**Additional information**
Screenshots, links to docs, etc.

**Comment by 1Enigma1** [comment]
pkg install git

**Comment by 1Enigma1** [comment]
chmod 777 infinite-bomber

**Comment by cp2004** [comment]
I have no idea why this happened, but no one else has reported it. I dug into it quite a bit at the time, as it looks like it's coming from within the print function. As this is not the only way to upgrade to Python 3, I won't be investigating this problem further.
