### ISSUE TITLE
Suppress pip's `Cache entry deserialization failed` messages

### ISSUE THREAD

**Issue by cp2004** [cp2004/Octoprint-Upgrade-To-Py3#56]
They've scared people and resulted in some cancelled upgrades. Suppressing *just* these will be OK and prevent panic.

**Comment by AntoineTurmel** [comment]
I still get those but checked here ;)

![image](https://user-images.githubusercontent.com/119288/163825626-bffde698-97ad-44f6-92eb-2a369f22e2ab.png)

**Comment by cp2004** [comment]
Yeah I never actually implemented it, since most people had upgraded so there's less need and I don't have time for all the testing needed. I just got a couple of confused people cancelling it so it seemed like a good idea at the time.
